### PR TITLE
enforce singleton destruction

### PR DESCRIPTION
**Pull request by artivis**
I had a print in the SensorFactory destructor and it never showed up :s 
This commit ensure that it is called.

### CODE REVIEW

**Comment by joansola** [comment]
Nice design! I did not know this use of static could be done!

**Comment by artivis** [comment]
actually me neither. Catching up on singleton.
I keep sending you merge request because I can't push (at all) directly on your repo (IRI-MobileRobotics/wolf) but only on mine (my fork) and this whatever the branch (factory or a locally created my_local_factory).
Can you please check my access permissions ??

**Comment by joansola** [comment]
OH, sure

**Comment by joansola** [comment]
done!

**Comment by artivis** [comment]
Thanks!

**Pull request merged**
