### PR TITLE
Matrix quaternion tools

### PR DESCRIPTION
**Pull request by AtDinesh**
I imported the spatial part of Pinocchio. Most of the functions we need (q2v, v2q, ...) are defined there.

### CODE REVIEW

**Comment by AtDinesh** [comment]
Next step would be to code quaternion/matrix tools that gives jacobians in output

**Comment by joansola** [comment]
Hi Dinesh. Before pulling to master, you need to do some extra work:
 - You should select the files you want to add to WOLF. All that is related to forces is not needed in WOLF.
 - Also, you should migrate all the syntax and name styles to the styles we use in WOLF.

**Comment by AtDinesh** [comment]
I am closing this pull request. This work is being done in a branch derived from matrix_quaternion_tools. i will merge it to this branch when it will be ready (if it is computationally interesting). For now I am putting qProd, v2q, (etc...) methods that can compute jacobians in the matrix_quaternion_tools branch.

**Comment by joansola** [comment]
Please post further comments to this issue in #54

**Pull request closed without merging**
